
# Name of your site (displayed in the header)
title: Plus62 Store
name: Plus62 Store
author: NdanG

# Short bio or description (displayed in the header)
description: Produk & Jasa Bordir Tasikmalaya

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/logo.png
promo: /images/promo.jpeg
image: /images/p62s.png

#
# Flags below are optional
#

collections:
  blogpost:
    output: true

comen: 30234
sitekey: 6LdSeuwZAAAAAPgWy6REloO70SStpBewNGuGmTkG
fb-pixel: 
fb-appID: 
fb-admin: 
fb-profile: 
fb-pages: 
signal-id: 23925364-ab76-466d-b529-44ea74b5d7c1
google_analytics: UA-187631685-1
dana-pay: https://link.dana.id/p2m?params=[orderId=c8c9ea7c-8b86-421d-987d-ebcf2d5604bf]
dana-diskon: https://link.dana.id/p2m?params=[orderId=534a046a-07ee-46c9-a7cd-0a54552e212a]

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: 

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

paginate: 16
paginate_path: '/page-:num'

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
